### ISSUE TITLE
莫名报错

### ISSUE THREAD

**Issue by 1zhangyy1** [Ksuriuri/EasyAIVtuber#1]
pygame 2.5.2 (SDL 2.28.2, Python 3.10.8)
Hello from the pygame community. https://www.pygame.org/contribute.html
free(): invalid pointer
大佬这个我怎么都解决不了，抱歉我有点点小白，在autodl上跑的

**Comment by Ksuriuri** [comment]
要在windows系统上才能保证正常运行哦，autodl用的应该是Ubuntu
